// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzwcgncutbpcwvuqeaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6d2NnbmN1dGJwY3d2dXFlYXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODUxNjMsImV4cCI6MjA2ODM2MTE2M30.nrlgmSSB4Gc8t22OGk-9fDbcgkZ6zMnETIn4j5lNVaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});