// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfprqgdzmrszsbklhlfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcHJxZ2R6bXJzenNia2xobGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjA5MjIsImV4cCI6MjA2ODUzNjkyMn0.r4b2vNnnIqiGzWgT8PKaZ7Qap_mz0-K4UyKyRpufaEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});